//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Network
    {
        public string AssetID { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<bool> OnlineStatus { get; set; }
        public Nullable<decimal> netSpeed { get; set; }
        public Nullable<decimal> netQuality { get; set; }
    }
}
