//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess2
{
    using System;
    using System.Collections.Generic;

    public partial class Software
    {
        public string AssetID { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<bool> DFStatus { get; set; }
        public Nullable<bool> CMStatus { get; set; }
        public Nullable<bool> GKStatus { get; set; }
        public Nullable<bool> ServicesPipeStatus { get; set; }
    }
}
